# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Recommendation.destroy_all
Spot.destroy_all
User.destroy_all
Category.destroy_all
Neighborhood.destroy_all

Recommendation.reset_pk_sequence
Spot.reset_pk_sequence
User.reset_pk_sequence
Category.reset_pk_sequence
Neighborhood.reset_pk_sequence

##############  Users 
user1= User.create(first_name: "Bella", last_name: "Evalle", username: "bella", password: "abc123", bio: "I like to try different food.")
user2= User.create(first_name: "Waverley", last_name: "Leung", username: "wavey", password: "abc123", bio: "I like to explore and eat good food.")

############ Categories
category1= Category.create(name: "Bar")
category2= Category.create(name: "Coffee & Tea")
category3= Category.create(name: "Cultural Center")
category4= Category.create(name: "Dog Park")
category5= Category.create(name: "Live Music Venue")
category6= Category.create(name: "Museum")
category7= Category.create(name: "Observation Deck")
category8= Category.create(name: "Park")
category9= Category.create(name: "Performing Arts Venue")
category10= Category.create(name: "Restaurant")
category11= Category.create(name: "Rock-climbing Gym")
category12= Category.create(name: "Shopping")
category13= Category.create(name: "Zoo")

############## Neighborhoods
## Bronx
neighborhood1= Neighborhood.create(name: "Belmont")
neighborhood2= Neighborhood.create(name: "Kingsbridge")
neighborhood3= Neighborhood.create(name: "Mott Haven")
neighborhood4= Neighborhood.create(name: "Riverdale")
neighborhood5= Neighborhood.create(name: "University Heights")

## Brooklyn
neighborhood6= Neighborhood.create(name: "Bedford-Stuyvesant")
neighborhood7= Neighborhood.create(name: "Bushwick")
neighborhood8= Neighborhood.create(name: "Dumbo")
neighborhood9= Neighborhood.create(name: "Greenpoint")
neighborhood10= Neighborhood.create(name: "Williamsburg")

## Manhattan
neighborhood11= Neighborhood.create(name: "Greenwich Village")
neighborhood12= Neighborhood.create(name: "Harlem")
neighborhood13= Neighborhood.create(name: "Lower East Side")
neighborhood14= Neighborhood.create(name: "Midtown")
neighborhood15= Neighborhood.create(name: "SoHo")

## Queens
neighborhood16= Neighborhood.create(name: "Astoria")
neighborhood17= Neighborhood.create(name: "Jamaica")
neighborhood18= Neighborhood.create(name: "Long Island City")
neighborhood19= Neighborhood.create(name: "Sunnyside")
neighborhood20= Neighborhood.create(name: "Woodside")

## Staten Island
neighborhood21= Neighborhood.create(name: "Great Kills")
neighborhood22= Neighborhood.create(name: "New Dorp")
neighborhood23= Neighborhood.create(name: "St. George")
neighborhood24= Neighborhood.create(name: "Todt Hill")
neighborhood25= Neighborhood.create(name: "West Brighton")


############ Spots
## Bronx (Belmont #1)
spot1= Spot.create(name: "Antonio's", address: "2370 Belmont Ave Bronx, NY 10458", info: "Italian, Pizza, Desserts /n (718) 733-6630 /n 11:30AM - 10:00PM", category: category10, neighborhood: neighborhood1)
spot2= Spot.create(name: "Bronx Zoo", address: "2300 Southern Blvd, The Bronx, NY 10460", info: "Zoo /n (718) 367-1010 /n 10:00AM - 5:30PM", category: category13, neighborhood: neighborhood1)
spot3= Spot.create(name: "Cafe al Mercato", address: "2344 Arthur Ave Bronx, NY 10458", info: "Italian, Pizza, Desserts /n 718) 364-7681/n 09:00AM - 08:00PM", category: category10, neighborhood: neighborhood1)
## Bronx (Kingsbridge #2)
spot4= Spot.create(name: "Mon Amour Coffee & Wine", address: "234 W 238 St. Bronx, NY 10463", info: "Coffee & Tea, Wine Bars, Beer Bar /n (718) 708-7804
/n 09:00AM - 08:00PM", category: category10, neighborhood: neighborhood2)
spot5= Spot.create(name: " Leche Y Miel Restaurant", address: "5761 Broadway Bronx, NY 10463", info: "Comfort Food, Dominican, Juice Bars & Smoothies /n (718) 708-5787 /n 11:00AM - 10:00PM", category: category10, neighborhood: neighborhood2)
spot6= Spot.create(name: "The Bronx Public", address: "170 W 231st St Bronx, NY 10463", info: "Sports Bars, American (Traditional) /n (718) 708-6447 /n 2:00PM - 10:00PM", category: category10, neighborhood: neighborhood2)
## Bronx (Mott Haven #3)
spot7= Spot.create(name: "Mott Haven Bagel & Barista Cafe", address: "221 E 138th St Mott Haven Bronx, NY 10451", info: "Cafes, Bagels, Burgers /n (718) 292-0600 /n
6:00AM - 5:00PM", category: category2, neighborhood: neighborhood3)
spot8= Spot.create(name: " La Morada", address: "308 Willis Ave Bronx, NY 10454", info: "Mexican, Vegetarian /n (718) 292-0235 /n
11:00AM - 6:30PM", category: category10, neighborhood: neighborhood3)
spot9= Spot.create(name: "Charlie’s Bar & Kitchen", address: "112 Lincoln Ave Bronx, NY 10454", info: "Cocktail Bars, Southern, American(Traditional) /n (718) 684-2338 /n
4:00PM - 11:00PM", category: category10, neighborhood: neighborhood3)
## Bronx (Riverdale #4)
spot10= Spot.create(name: "Aoyu Sushi", address: "3532  A Johnson Ave Bronx, NY 10463", info: "Japanese, Sushi Bars, Salad /n (718) 884-6633 /n
11:30AM - 3:15PM, 4:30PM-9:45PM ", category: category10, neighborhood: neighborhood4)
spot11= Spot.create(name: "Seton Park", address: "Independence Ave, The Bronx, NY 10463", info: "Park /n (212) 639-9675 /n
Hours or services may differ", category: category8, neighborhood: neighborhood4)
spot12= Spot.create(name: "The Hill Bistro", address: "3541 Riverdale Ave Bronx, NY 10463", info: "American(Traditional), Wine Bars /n (718) 708-7770 /n 3:00PM - 01:00AM", category: category10, neighborhood: neighborhood4)
## Bronx (University Heights #5)
spot13= Spot.create(name: "Salsa Con Fuego", address: "2297 Cedar Ave Bronx, NY 10468", info: "Bars, Latin American /n (718) 561-6161 /n 5:00PM - 4:00AM", category: category10, neighborhood: neighborhood5)
spot14= Spot.create(name: "Dallas BBQ", address: "281 W Fordham Rd Bronx, NY 10468", info: "Barbeque /n (718) 220-2822 /n 1:00PM - 9:00PM", category: category10, neighborhood: neighborhood5)
spot15= Spot.create(name: "Hall of Fame for Great Americans", address: "2070 Sedgwick Ave Bronx, NY 10453", info: "Museums /n (718) 289-5146 /n 10:00AM - 4:00PM", category: category6, neighborhood: neighborhood5)

# ## Brooklyn (Bedford-Stuyvesant #6)
# spot16= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood6)
# spot17= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood6)
# spot18= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood6)
# ## Brooklyn (Bushwick #7)
# spot19= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood7)
# spot20= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood7)
# spot21= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood7)
# ## Brooklyn (Dumbo #8)
# spot22= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood8)
# spot23= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood8)
# spot24= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood8)
# ## Brooklyn (Greenpoint #9)
# spot25= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood9)
# spot26= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood9)
# spot27= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood9)
# ## Brooklyn (Williamsburg #10)
# spot28= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood10)
# spot29= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood10)
# spot30= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood10)

# ## Manhattan (Greenwich Village #11)
# spot31= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood11)
# spot32= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood11)
# spot33= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood11)
# ## Manhattan (Harlem #12)
# spot34= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood12)
# spot35= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood12)
# spot36= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood12)
# ## Manhattan (Lower East Side #13)
# spot37= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood13)
# spot38= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood13)
# spot39= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood13)
# ## Manhattan (Midtown #14)
# spot40= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood14)
# spot41= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood14)
# spot42= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood14)
# ## Manhattan (SoHo #15)
# spot43= Spot.create(name: "", adress: "", info: "",  category: category, neighborhood: neighborhood15)
# spot44= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood15)
# spot45= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood15)

# ## Queens (Astoria #16)
# spot46= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood16)
# spot47= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood16)
# spot48= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood16)
# ## Queens (Jamaica #17)
# spot49= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood17)
# spot50= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood17)
# spot51= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood17)
# ## Queens (Long Island City #18)
# spot52= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood18)
# spot53= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood18)
# spot54= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood18)
# ## Queens (Sunnyside #19)
# spot55= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood19)
# spot56= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood19)
# spot57= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood19)
# ## Queens (Woodside #20)
# spot58= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood20)
# spot59= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood20)
# spot60= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood20)

# ## Staten Island (Great Kills #21)
# spot61= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood21)
# spot62= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood21)
# spot63= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood21)
# ## Staten Island (New Dorp #22)
# spot64= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood22)
# spot65= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood22)
# spot66= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood22)
# ## Staten Isalnd (St.George #23)
# spot67= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood23)
# spot68= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood23)
# spot69= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood23)
# ## Staten Island (Todt Hill #24)
# spot70= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood24)
# spot71= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood24)
# spot72= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood24)
# ## Staten Island (West Brighton #25)
# spot73= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood25)
# spot74= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood25)
# spot75= Spot.create(name: "", address: "", info: "", category: category, neighborhood: neighborhood25)


############ Recommendations
## Bronx (Belmont #1)
recommendation1 = Recommendation.create(context: "Fettuccine Carbonara - Creamy buttery sauce with the perfect amount of salt and a little hint of sweet onion. Such a delicacy.", user: user1, spot: spot1)
recommendation2 = Recommendation.create(context: "Was pleasantly surprised at how much fun we had. Very clean facilities, and not too crowded due to COVID restrictions on the amount of people they let in each day. Two lines were long: The line to the gorilla camp and the merry go round as they only let so many people in at once, but the rest of the zoo was less crowded. A fun family day.", user: user1, spot: spot2)
recommendation3 = Recommendation.create(context: "Every single item here is incredible. This is one of the best eggplant slices I have ever had (and I've had a lot!). I've tried almost every variety of slice they have and each one has been better than the next. The focaccia sandwiches are outta this world! This is a must try and belongs on Best Of lists in NYC.", user: user1, spot: spot3)
## Bronx (Kingsbridge #2)
recommendation4 = Recommendation.create(context: "Friendly staff, cozy atmosphere and most important, excellent coffee and food. Great place for happy hour, nice beer selection.", user: user1, spot: spot4)
recommendation5 = Recommendation.create(context: "A lovely restaurant with great service and a friendly welcoming local atmosphere.", user: user1, spot: spot5)
recommendation6 = Recommendation.create(context: "The staff are amazing, the food delicious and drinks, aren't watered down. You have to try it for yourself.", user: user1, spot: spot6)
## Bronx (Mott Haven #3)
recommendation7 = Recommendation.create(context: "Order an everything bagel  toasted with egg and cheese.   It's a bagel. It's nyc if it's not good there's a problem big time. I ordered they  gave me a great product I enjoyed it would for sure stop by again and get another one.", user: user1, spot: spot7)
recommendation8 = Recommendation.create(context: "Delicious food, some of the best aguas frescas you can get anywhere in NYC, and a really wonderful staff who put the money from the restaurant towards important social justice movements that affect the lives of thousands of New Yorkers and their families. Can not recommend more highly! Try the chilaquiles, enchiladas, mole & chile rellenos", user: user1, spot: spot8)
recommendation9 = Recommendation.create(context: "Pretty chill, laid back spot. Good service. Great food. Their Truffle Mac & Cheese is Everything!!", user: user1, spot: spot9)
## Bronx (Riverdale #4)
recommendation10 = Recommendation.create(context: "Most trust worthy sushi spot/ fresh &clean.well reserved! they are polite and I love their lounge music- makes it more cozy and welcoming.", user: user1, spot: spot10)
recommendation11 = Recommendation.create(context: "Very safe and clean. Great park to exercise at night. Needs more lighting. Dog park, basketball court and children park with sprinklers (renovation still ongoing). There is bathroom space. Lots of trees and picnic areas.", user: user1, spot: spot11)
recommendation12 = Recommendation.create(context: "Food is always delicious and perfectly cooked. Love the  ambiance and service! Highly recommended The Hill Bistro!", user: user1, spot: spot12)
## Bronx (University Heights #5)
recommendation13 = Recommendation.create(context: "Love Salsa con fuego. The food is great, music is on point! Drinks are reasonable and delicious.", user: user1, spot: spot13)
recommendation14 = Recommendation.create(context: "I'm back. Love me some Dallas BBQ.
This is my gotta have place. And each time it is shrimp & wing combo (sticky of course), corn on cob and Texas Ginger ale. It is the ultimate hunger fixer. Take a full to go is the only way to leave. It's the hook up. Nice way to spend a Friday afternoon.", user: user1, spot: spot14)
recommendation15 = Recommendation.create(context: "A setting so grand, You could draw the masses displaying dog poop in this Stanford White designed structure perched overlooking the hudson at the edge of bronx community college. Instead, you'll find an amazing winding tour of life-like sculptures of great Americans, from Adams to Washington. The adjacent library, also designed by Standord White, is worth exploring and makes for a beautiful backdrop for this forgotten New York treasure.", user: user1, spot: spot15)

# ## Brooklyn (Bedford-Stuyvesant #6)
# recommendation16 = Recommendation.create(context: "", user: user1, spot: spot16)
# recommendation17 = Recommendation.create(context: "", user: user1, spot: spot17)
# recommendation18 = Recommendation.create(context: "", user: user1, spot: spot18)
# ## Brooklyn (Bushwick #7)
# recommendation19 = Recommendation.create(context: "", user: user1, spot: spot19)
# recommendation20 = Recommendation.create(context: "", user: user1, spot: spot20)
# recommendation21 = Recommendation.create(context: "", user: user1, spot: spot21)
# ## Brooklyn (Dumbo #8)
# recommendation22 = Recommendation.create(context: "", user: user1, spot: spot22)
# recommendation23 = Recommendation.create(context: "", user: user1, spot: spot23)
# recommendation24 = Recommendation.create(context: "", user: user1, spot: spot24)
# ## Brooklyn (Greenpoint #9)
# recommendation25 = Recommendation.create(context: "", user: user1, spot: spot25)
# recommendation26 = Recommendation.create(context: "", user: user1, spot: spot26)
# recommendation27 = Recommendation.create(context: "", user: user1, spot: spot27)
# ## Brooklyn (Williamsburg #10)
# recommendation28 = Recommendation.create(context: "", user: user1, spot: spot28)
# recommendation29 = Recommendation.create(context: "", user: user1, spot: spot29)
# recommendation30 = Recommendation.create(context: "", user: user1, spot: spot30)

# ## Manhattan (Greenwich Village #11)
# recommendation31 = Recommendation.create(context: "", user: user1, spot: spot31)
# recommendation32 = Recommendation.create(context: "", user: user1, spot: spot32)
# recommendation33 = Recommendation.create(context: "", user: user1, spot: spot33)
# ## Manhattan (Harlem #12)
# recommendation34 = Recommendation.create(context: "", user: user1, spot: spot34)
# recommendation35 = Recommendation.create(context: "", user: user1, spot: spot35)
# recommendation36 = Recommendation.create(context: "", user: user1, spot: spot36)
# ## Manhattan (Lower East Side #13)
# recommendation37 = Recommendation.create(context: "", user: user1, spot: spot37)
# recommendation38 = Recommendation.create(context: "", user: user1, spot: spot38)
# recommendation39 = Recommendation.create(context: "", user: user1, spot: spot39)
# ## Manhattan (Midtown #14)
# recommendation40 = Recommendation.create(context: "", user: user1, spot: spot40)
# recommendation41 = Recommendation.create(context: "", user: user1, spot: spot41)
# recommendation42 = Recommendation.create(context: "", user: user1, spot: spot42)
# ## Manhattan (SoHo #15)
# recommendation43 = Recommendation.create(context: "", user: user1, spot: spot43)
# recommendation44 = Recommendation.create(context: "", user: user1, spot: spot44)
# recommendation45 = Recommendation.create(context: "", user: user1, spot: spot45)
# ## Queens (Astoria #16)
# recommendation46 = Recommendation.create(context: "", user: user1, spot: spot46)
# recommendation47 = Recommendation.create(context: "", user: user1, spot: spot47)
# recommendation48 = Recommendation.create(context: "", user: user1, spot: spot48)
# ## Queens (Jamaica #17)
# recommendation49 = Recommendation.create(context: "", user: user1, spot: spot49)
# recommendation50 = Recommendation.create(context: "", user: user1, spot: spot50)
# recommendation51 = Recommendation.create(context: "", user: user1, spot: spot51)
# ## Queens (Long Island City #18)
# recommendation52 = Recommendation.create(context: "", user: user1, spot: spot52)
# recommendation53 = Recommendation.create(context: "", user: user1, spot: spot53)
# recommendation54 = Recommendation.create(context: "", user: user1, spot: spot54)
# ## Queens (Sunnyside #19)
# recommendation55 = Recommendation.create(context: "", user: user1, spot: spot55)
# recommendation56 = Recommendation.create(context: "", user: user1, spot: spot56)
# recommendation57 = Recommendation.create(context: "", user: user1, spot: spot57)
# ## Queens (Woodside #20)
# recommendation58 = Recommendation.create(context: "", user: user1, spot: spot58)
# recommendation59 = Recommendation.create(context: "", user: user1, spot: spot59)
# recommendation60 = Recommendation.create(context: "", user: user1, spot: spot60)

# ## Staten Island (Great Kills #21)
# recommendation61 = Recommendation.create(context: "", user: user1, spot: spot61)
# recommendation62 = Recommendation.create(context: "", user: user1, spot: spot62)
# recommendation63 = Recommendation.create(context: "", user: user1, spot: spot63)
# ## Staten Island (New Dorp #22)
# recommendation64 = Recommendation.create(context: "", user: user1, spot: spot64)
# recommendation65 = Recommendation.create(context: "", user: user1, spot: spot65)
# recommendation66 = Recommendation.create(context: "", user: user1, spot: spot66)
# ## Staten Island (St. George #23)
# recommendation67 = Recommendation.create(context: "", user: user1, spot: spot67)
# recommendation68 = Recommendation.create(context: "", user: user1, spot: spot68)
# recommendation69 = Recommendation.create(context: "", user: user1, spot: spot69)
# ## Staten Island (Todt Hill #24)
# recommendation70 = Recommendation.create(context: "", user: user1, spot: spot70)
# recommendation71 = Recommendation.create(context: "", user: user1, spot: spot71)
# recommendation72 = Recommendation.create(context: "", user: user1, spot: spot72)
# ## Staten Island (West Brighton #25)
# recommendation73 = Recommendation.create(context: "", user: user1, spot: spot73)
# recommendation74 = Recommendation.create(context: "", user: user1, spot: spot74)
# recommendation75 = Recommendation.create(context: "", user: user1, spot: spot75)

## Manhattan - (Neighborhood)
# spot1= Spot.create(name: "Wildair", address: "142 Orchard St, New York, NY 10002", info: "New American", category: category1, neighborhood: neighborhood1)

# ## Bronx - Riverdale
# spot2 = Spot.create(name: "Aoyu Sushi", address: "3532  A Johnson Ave Bronx, NY 10463", info: "Japanese, Sushi Bars, Salad /n (718) 884-6633 /n 11:30AM - 3:15PM, 4:30PM-9:45PM", category: category1, neighborhood: neighborhood4)

# recommendation1 = Recommendation.create(context: "This restaurant offers excellent service and tasty Korean dishes.", user: user1, spot: spot1)

# recommendation2 = Recommendation.create(context: "Most trust worthy sushi spot/ fresh &clean.well reserved! they are polite and I love their lounge music- makes it more cozy and welcoming", user: user1, spot: spot2)

puts "meow"